#!/bin/bash

COMMAND="$@"
CURRENTPATH=`pwd`
SCRIPTPATH=`dirname "$(readlink -f "$0")"`

URL="http://127.0.0.1:$PORT/frostybot"

for x in "log" "dbupgrade"; do
    if [ "$1" == "$x" ]; then
        cd "$SCRIPTPATH"
        PARAM="${COMMAND/$x/''}"
        eval "./scripts/$x $PARAM"
        cd "$CURRENTPATH"
        exit
    fi
done

WGETCMD="wget --no-check-certificate --method POST --header 'accept: application/json' --header 'cache-control: no-cache' --header 'Content-Type: text/plain' --body-data '$COMMAND' -qO- $URL"
eval "$WGETCMD | jq"
